---
services:
  db:
    image: postgres:18.3
    container_name: dev_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: thoughts
      POSTGRES_PASSWORD: thoughts_local
      POSTGRES_DB: LMS
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql"

  mailpit:
    image: axllent/mailpit:v1.29
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
