"""update: add status enum

Revision ID: 2f69f9cfc438
Revises: 849961d9691b
Create Date: 2026-04-24 14:50:27.962958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f69f9cfc438'
down_revision: Union[str, Sequence[str], None] = '849961d9691b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('status', sa.Enum('draft', 'published', 'archived', name='content_status'), nullable=False))
    op.add_column('quiz', sa.Column('status', sa.Enum('draft', 'published', 'archived', name='content_status'), nullable=False))
    op.add_column('training_path', sa.Column('status', sa.Enum('draft', 'published', 'archived', name='content_status'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_path', 'status')
    op.drop_column('quiz', 'status')
    op.drop_column('lesson', 'status')
    # ### end Alembic commands ###
