"""update aggregate ids to have a position for later use

Revision ID: 387cccd46442
Revises: 2f69f9cfc438
Create Date: 2026-04-27 14:46:44.395754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387cccd46442'
down_revision: Union[str, Sequence[str], None] = '2f69f9cfc438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'position')
    # ### end Alembic commands ###
