"""add join table

Revision ID: 7411859a2cdc
Revises: a6d496c6a4cf
Create Date: 2026-04-01 14:22:51.106811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7411859a2cdc'
down_revision: Union[str, Sequence[str], None] = 'a6d496c6a4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_training_path',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('training_path_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['training_path_id'], ['training_path.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'training_path_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_training_path')
    # ### end Alembic commands ###
