"""make all models with a title column unique

Revision ID: 849961d9691b
Revises: 2356107a3f36
Create Date: 2026-04-23 15:36:26.061711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '849961d9691b'
down_revision: Union[str, Sequence[str], None] = '2356107a3f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'lesson', ['title'])
    op.create_unique_constraint(None, 'quiz', ['title'])
    op.create_unique_constraint(None, 'training_path', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_path', type_='unique')
    op.drop_constraint(None, 'quiz', type_='unique')
    op.drop_constraint(None, 'lesson', type_='unique')
    # ### end Alembic commands ###
