"""initial schema

Revision ID: a6d496c6a4cf
Revises:
Create Date: 2026-04-01 13:52:14.670520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a6d496c6a4cf"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_path",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("department", sa.Enum(name="department"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_account",
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=15), nullable=False),
        sa.Column("last_name", sa.String(length=20), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("department", sa.Enum(name="department"), nullable=False),
        sa.Column("user_type", sa.Enum(name="user_type"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("completed_lessons", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("completed_quizzes", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column(
            "completed_training_paths", postgresql.ARRAY(sa.UUID()), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "lesson",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("material_path", sa.String(), nullable=False),
        sa.Column("training_path_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["training_path_id"],
            ["training_path.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quiz",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lesson.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "question",
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("answer", sa.String(), nullable=False),
        sa.Column("possible_answers", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("quiz_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quiz.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question")
    op.drop_table("quiz")
    op.drop_table("lesson")
    op.drop_table("user_account")
    op.drop_table("training_path")
    # ### end Alembic commands ###
